[sharktank] In eager do not use kernel for fp4 matmul
The wave_mxfp4_bmm kernel works only for some AMD GPU architectures.
```
error: 'amdgpu.scaled_mfma' op scaled MFMA only supported on gfx908+
```

It is also desirable to have eager execution path that does not depend on IREE.
This would allow us to have a simple reference implementation that we can test
against.

In eager we dequantize the arguments and run a "normal" matmul.