[model_tuner] Fix double-registration of option
Since the option renaming in `b19f0f8759a376706935f94d9dd1f7b21cda2ee5`, the
model tuner fails during argument parsing due to multiple options having
the same name. The option is only used in `model_tuner.py`, so I've kept
the one registered there.
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/rkayaith/repos/shark-ai/sharktuner/model_tuner/__main__.py", line 9, in <module>
    model_tuner.main()
  File "/home/rkayaith/repos/shark-ai/sharktuner/model_tuner/model_tuner.py", line 79, in main
    args = arg_parse()
           ^^^^^^^^^^^
  File "/home/rkayaith/repos/shark-ai/sharktuner/model_tuner/model_tuner.py", line 74, in arg_parse
    args = libtuner.parse_arguments(parser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rkayaith/repos/shark-ai/sharktuner/sharktuner/libtuner.py", line 281, in parse_arguments
    general_args.add_argument(
  File "/usr/lib/python3.12/argparse.py", line 1500, in add_argument
    return self._add_action(action)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 1705, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 1514, in _add_action
    self._check_conflict(action)
  File "/usr/lib/python3.12/argparse.py", line 1654, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/usr/lib/python3.12/argparse.py", line 1663, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --num-model-candidates: conflicting option string: --num-model-candidates
```